# Generated by Django 3.1.3 on 2020-11-03 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(blank=True, max_length=60)),
                ('farmer_photo', pyuploadcare.dj.models.ImageField(blank=True)),
                ('farmer_bio', models.TextField(blank=True, max_length=500)),
                ('farm_name', models.CharField(blank=True, max_length=60)),
                ('farm_photo', pyuploadcare.dj.models.ImageField(blank=True)),
                ('farm_description', models.TextField(blank=True, max_length=500)),
                ('farm_location', models.CharField(blank=True, max_length=60)),
                ('farm_tel', models.CharField(blank=True, max_length=60)),
                ('farm_email', models.EmailField(blank=True, max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
